# Generated by Django 3.2.8 on 2021-10-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complate',
            new_name='complete',
        ),
    ]
